name: Build docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR container register
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # tag the image with a version when adding a git tag that starts with 'v'
      - name: Build and push tagged image
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/pricefeeder:${{ steps.get_version.outputs.version-without-v }}

      # tag the image with :latest when pushing to master
      - name: Build and push latest image
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/pricefeeder:latest
